version: "3"

services:
  app:
    build: .         
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    container_name: 'database-mysql'
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=reload-test
      - MYSQL_DATABASE=reload
      - MYSQL_USER=reload_user
      - MYSQL_PASSWORD=reload-test

  redis:
    image: redis:5.0.3-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - .:/data
    